"""Standardized candidate résumé as a PDF, rendered with fpdf2 (pure Python — no
LibreOffice). One fixed Ledgerline template so every candidate looks identical.
Input is the `_full` candidate dict from routers.candidates."""
from __future__ import annotations

from fpdf import FPDF

NAVY = (15, 23, 42)      # slate-900
BLUE = (3, 105, 161)     # sky-700
SLATE = (71, 85, 105)    # slate-600
MUTED = (148, 163, 184)  # slate-400
LINE = (226, 232, 240)   # slate-200

# Core fonts are latin-1 only; normalize common unicode + drop the rest.
_REPL = {"—": "-", "–": "-", "’": "'", "‘": "'", "“": '"', "”": '"', "…": "...", " ": " "}


def _txt(s) -> str:
    s = str(s or "")
    for k, v in _REPL.items():
        s = s.replace(k, v)
    return s.encode("latin-1", "replace").decode("latin-1")


class _Resume(FPDF):
    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*MUTED)
        self.cell(0, 6, _txt("Generated by Ledgerline"), align="C")


def _heading(pdf: _Resume, label: str):
    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*BLUE)
    pdf.cell(0, 7, _txt(label.upper()), new_x="LMARGIN", new_y="NEXT")
    y = pdf.get_y()
    pdf.set_draw_color(*LINE)
    pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
    pdf.ln(2)


def build_resume_pdf(c: dict) -> bytes:
    pdf = _Resume(format="A4", unit="mm")
    pdf.set_auto_page_break(True, margin=18)
    pdf.set_margins(18, 16, 18)
    pdf.add_page()
    width = pdf.w - pdf.l_margin - pdf.r_margin

    # ── header band ──
    pdf.set_fill_color(*NAVY)
    pdf.rect(0, 0, pdf.w, 34, style="F")
    pdf.set_xy(pdf.l_margin, 9)
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(255, 255, 255)
    name = _txt(c.get("full_name") or "Candidate")
    cred = _txt(c.get("credential") or "")
    pdf.cell(0, 9, name + ("  ·  " + cred if cred else ""), new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(pdf.l_margin)
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(186, 230, 253)  # sky-200
    pdf.cell(0, 7, _txt(c.get("role_title") or ""), new_x="LMARGIN", new_y="NEXT")

    # ── quick facts row ──
    pdf.set_y(40)
    facts = []
    if c.get("experience_label"):
        facts.append(("Experience", _txt(c["experience_label"])))
    if c.get("price_monthly") is not None:
        facts.append(("Rate", f"${int(c['price_monthly']):,}/mo"))
    if c.get("availability"):
        facts.append(("Availability", _txt(c["availability"])))
    if c.get("location"):
        facts.append(("Location", _txt(c["location"])))
    if facts:
        col = width / len(facts)
        x0 = pdf.l_margin
        for lbl, val in facts:
            pdf.set_xy(x0, 40)
            pdf.set_font("Helvetica", "", 7.5)
            pdf.set_text_color(*MUTED)
            pdf.cell(col, 4, _txt(lbl.upper()), new_x="LMARGIN", new_y="NEXT")
            pdf.set_x(x0)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(*NAVY)
            pdf.cell(col, 6, val)
            x0 += col
        pdf.set_y(52)

    def section_text(label, body):
        _heading(pdf, label)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*SLATE)
        pdf.multi_cell(width, 5.2, _txt(body))

    def section_chips(label, items):
        _heading(pdf, label)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*SLATE)
        pdf.multi_cell(width, 5.2, _txt("  •  ".join(items)))

    if c.get("about"):
        section_text("About", c["about"])
    if c.get("skills"):
        section_chips("Skills", c["skills"])
    if c.get("software"):
        section_chips("Software", c["software"])
    if c.get("assessments"):
        _heading(pdf, "Assessments")
        for a in c["assessments"]:
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(*SLATE)
            pdf.cell(width * 0.55, 6, _txt(a.get("name", "")))
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*NAVY)
            pdf.cell(width * 0.45, 6, _txt(a.get("rating", "")), align="R", new_x="LMARGIN", new_y="NEXT")

    return bytes(pdf.output())
